// Generated by CoffeeScript 1.3.3
(function() {
  var HomeController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  HomeController = (function() {

    function HomeController() {
      this.index = __bind(this.index, this);

    }

    HomeController.prototype.index = function(req, res) {
      return res.send('Hello World from home controller');
    };

    return HomeController;

  })();

  module.exports = HomeController;

}).call(this);
