// Generated by CoffeeScript 1.3.3
(function() {
  var Express, requireExpress;

  requireExpress = function(resource) {
    return require("" + __dirname + "/express/" + resource);
  };

  Express = {
    require: requireExpress
  };

  module.exports = Express;

}).call(this);
