// Generated by CoffeeScript 1.3.3
(function() {
  var Express, requireExpress, resolve;

  resolve = require('path').resolve;

  requireExpress = function(resource) {
    return require("" + __dirname + "/express/" + resource);
  };

  Express = {
    require: requireExpress,
    root: resolve(__dirname, '..')
  };

  module.exports = Express;

}).call(this);
