// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function() {
    this.get('/', {
      to: 'home#index'
    });
    this.get('/foo', function(req, res) {
      console.log(req.route);
      console.log(req.query);
      console.log(req.headers);
      return res.send('<!doctype html>\
                <html>\
                  <head></head>\
                  <body>\
                    <form action="/foo" method="post">\
                      <input name="_method" type="hidden" value="put">\
                      <input name="text" type="text" value="test">\
                      <input type="submit" value="submit">\
                    </form>\
                  </body>\
                </html>');
    });
    return this.put('/foo', function(req, res) {
      console.log(req.route);
      console.log(req.body);
      console.log(req.headers);
      return res.send("Put was called");
    });
  };

}).call(this);
