// Generated by CoffeeScript 1.3.3
(function() {
  var Controller, bind;

  bind = function(fn, context) {
    return function() {
      return fn.apply(context, arguments);
    };
  };

  Controller = (function() {

    Controller.partialName = function() {
      return this.name.replace('Controller', '').toLowerCase();
    };

    Controller.crud = ['index', 'show', 'edit', 'update', 'create', 'destroy', 'new'];

    function Controller() {
      var key, _i, _len, _ref;
      _ref = Controller.crud;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        key = _ref[_i];
        this[key] = this.wrap(this[key]);
      }
    }

    Controller.prototype.wrap = function(method) {
      var _this = this;
      method = bind(method, this);
      return function() {
        return method.call(null, arguments);
      };
    };

    return Controller;

  })();

  module.exports = Controller;

}).call(this);
