// Generated by CoffeeScript 1.3.3
(function() {
  var __slice = [].slice;

  exports.express_project = function() {
    var args, cb, generator, _i;
    generator = arguments[0], args = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), cb = arguments[_i++];
  };

}).call(this);
